---
- name: install_archive | create release directory
  ansible.builtin.file:
    state: directory
    path: "{{ archive_dest }}"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: 0750

- name: install_archive | download
  ansible.builtin.get_url:
    url: "{{ archive_url }}/{{ archive_name }}"
    dest: "{{ archive_dest }}/{{ archive_name }}"
    checksum: "sha256:{{ archive_url }}/{{ archive_checksum }}"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: 0640
  register: archive_downloaded
  until: archive_downloaded is succeeded
  retries: 3
  delay: 5
  notify: restart nats-exporter service

- name: install_archive | unarchive
  ansible.builtin.unarchive:
    src: "{{ archive_dest }}/{{ archive_name }}"
    dest: "{{ archive_extract_dest }}"
    include: "{{ archive_extract_files | default(omit) }}"
    mode: 0755
    extra_opts: [--strip-components=1]
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    remote_src: yes
  when: archive_downloaded.changed
