---
- name: main | validate configuration
  ansible.builtin.include_tasks: "validate.yml"

- name: main | install server
  ansible.builtin.include_tasks: "server.yml"

- name: main | install cli
  ansible.builtin.include_tasks: "cli.yml"
  when: nats_cli_enabled|bool

- name: main | install prometheus exporter
  ansible.builtin.include_tasks: "exporter.yml"
  when: nats_exporter_enabled|bool
