---
- name: server | install package (debian)
  ansible.builtin.apt:
    deb: "https://github.com/nats-io/nats-server/releases/download/v{{ nats_version }}/nats-server-v{{ nats_version }}-amd64.deb"
    state: present
  register: install_server
  until: install_server is succeeded
  retries: 3
  delay: 5
  notify: restart nats service
  when: ansible_os_family == "Debian"

- name: server | install package (redhat)
  ansible.builtin.dnf:
    name: "https://github.com/nats-io/nats-server/releases/download/v{{ nats_version }}/nats-server-v{{ nats_version }}-amd64.rpm"
    disable_gpg_check: true
    state: present
  register: install_server
  until: install_server is succeeded
  retries: 3
  delay: 5
  notify: restart nats service
  when: ansible_os_family == "RedHat"

- name: server | create group
  ansible.builtin.group:
    name: "{{ nats_group }}"
    state: present

- name: server | create user
  ansible.builtin.user:
    name: "{{ nats_user }}"
    comment: "nats server user"
    group: "{{ nats_group }}"
    password: '!'
    shell: '/usr/sbin/nologin'

- name: server | configure log dir
  ansible.builtin.file:
    path: "{{ nats_log_dir }}"
    state: directory
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: '750'
  when: nats_log_enabled|bool

- name: server | configure logrotate
  ansible.builtin.template:
    src: logrotate.conf.j2
    dest: "/etc/logrotate.d/nats-server"
    mode: "0644"
  when: nats_log_enabled|bool

- name: server | configure jetstream storage dir
  ansible.builtin.file:
    path: "{{ nats_jetstream_storage_dir }}"
    state: directory
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: '750'
  when: nats_jetstream_enabled|bool

- name: "server | configure nats systemd service"
  ansible.builtin.template:
    src: nats.service.j2
    dest: "/etc/systemd/system/nats-server.service"
    mode: "0644"
  notify: restart nats service

- name: server | set accounts and users facts
  ansible.builtin.set_fact:
    __nats_users_authorization: "{{ nats_users | dict2items | selectattr('value.account', 'undefined') | list }}"
    __nats_accounts: "{{ nats_users.values() | selectattr('account', 'defined') | map(attribute='account') | unique | list }}"
    __nats_users_accounts: "{{ nats_users | dict2items | selectattr('value.account', 'defined') | list }}"

- name: server | configure nats server
  ansible.builtin.template:
    src: "nats.conf.j2"
    dest: "/etc/nats-server.conf"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: "0640"
  notify: restart nats service # it's not clear what settings can be reloaded so restart

- name: "server | enable and start nats service"
  ansible.builtin.service:
    name: nats-server
    state: started
    enabled: true

- name: server | restart nats service (force)
  ansible.builtin.debug:
    msg: "force restart for nats server is triggered"
  changed_when: true
  notify: restart nats service
  when: nats_force_restart|bool
