---
- name: restart nats service
  ansible.builtin.systemd:
    name: nats-server
    state: restarted
    daemon_reload: yes
  register: restarted

- name: reload nats service
  ansible.builtin.service:
    name: nats-server
    state: reloaded
  when: restarted is not defined

- name: restart nats-exporter service
  ansible.builtin.systemd:
    name: nats-exporter
    state: restarted
    daemon_reload: yes
  register: restarted
