---
name: molecule tests
on:
  push:
    branches:
      - main
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os:
          - rockylinux:8
          - rockylinux:9
          - debian:11
          - debian:12
    steps:
      # github ubuntu images uses podman 3.4.4 which is incompatible with molecule-plugins podman driver (podman 4.x is required)
      # next two actions are just workaround and can be removed when github podman will be updated
      - uses: gacts/install-podman@v1
      - run: podman version
      - uses: actions/checkout@v3
      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: dependencies
        run: pip3 install -r molecule/default/requirements.txt
      # molecule's lint stage was removed: https://github.com/ansible/molecule/discussions/3825#discussioncomment-4908366
      - name: lint
        run: |
          set -e
          yamllint .
          ansible-lint -p -v
          flake8
      - name: molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_IMAGE: ${{ matrix.os }}
